#!/usr/bin/env python3
"""Normalize case-only folder differences detected in relocate plan.

This tool consumes relocate_plan_*.jsonl generated by relocate_existing_files.py dry-run.
It extracts rows where src/dst are same path on case-insensitive comparison but differ in
letter case, then performs in-place two-step rename (old -> temp -> target) on directories.

Why plan-based:
- The relocate plan already uses DB `program_title` as source of truth.
- We can avoid re-implementing routing logic and keep behavior deterministic.
"""

from __future__ import annotations

import argparse
import os
import uuid
from pathlib import Path
from typing import Any

from pathscan_common import canonicalize_windows_path, iter_jsonl, safe_json, windows_to_wsl_path


def _split_win(p: str) -> list[str]:
    return canonicalize_windows_path(p).split("\\")


def _join_win(parts: list[str]) -> str:
    return "\\".join(parts)


def _extract_case_only_dirs(src: str, dst: str) -> list[tuple[str, str]]:
    """Return per-segment directory rename pairs (old_dir, new_dir).

    We collect only directory segments (exclude filename), and only where segment differs
    by case (`lower()` equal).
    """
    src_parts = _split_win(src)
    dst_parts = _split_win(dst)
    if len(src_parts) != len(dst_parts) or len(src_parts) < 2:
        return []
    out: list[tuple[str, str]] = []
    last_dir_idx = len(src_parts) - 2
    for i in range(1, last_dir_idx + 1):
        s = src_parts[i]
        d = dst_parts[i]
        if s == d:
            continue
        if s.lower() != d.lower():
            # Not case-only; handled by relocate apply, not this tool.
            continue
        old_dir = _join_win(src_parts[: i + 1])
        new_dir = _join_win(src_parts[:i] + [d])
        out.append((old_dir, new_dir))
    return out


def _normalize_ops(raw_ops: list[tuple[str, str]]) -> list[dict[str, Any]]:
    """Deduplicate operations and keep parent-first ordering."""
    uniq: dict[tuple[str, str], tuple[str, str]] = {}
    for old_dir, new_dir in raw_ops:
        key = (old_dir.lower(), new_dir.lower())
        uniq[key] = (old_dir, new_dir)
    ordered = sorted(uniq.values(), key=lambda p: p[0].count("\\"))
    return [{"old": old, "new": new} for old, new in ordered]


def _rename_case_only_dir(old_win: str, new_win: str) -> dict[str, Any]:
    old_wsl = windows_to_wsl_path(old_win)
    new_wsl = windows_to_wsl_path(new_win)
    old_p = Path(old_wsl)
    new_p = Path(new_wsl)

    if old_win.lower() != new_win.lower() or old_win == new_win:
        return {"ok": False, "error": "not_case_only_pair", "old": old_win, "new": new_win}
    if not old_p.exists():
        if new_p.exists():
            return {"ok": True, "status": "already_normalized", "old": old_win, "new": new_win}
        return {"ok": False, "error": "src_not_found", "old": old_win, "new": new_win}

    parent = old_p.parent
    temp_name = f"__casefix_tmp__{uuid.uuid4().hex[:10]}"
    temp_p = parent / temp_name
    try:
        os.rename(old_p, temp_p)
        os.rename(temp_p, parent / Path(new_wsl).name)
        return {"ok": True, "status": "renamed", "old": old_win, "new": new_win}
    except Exception as e:
        try:
            if temp_p.exists() and not old_p.exists():
                os.rename(temp_p, old_p)
        except Exception:
            pass
        return {"ok": False, "error": str(e), "old": old_win, "new": new_win}


def main() -> int:
    ap = argparse.ArgumentParser(description="Normalize case-only directory differences from relocate plan")
    ap.add_argument("--plan", required=True, help="Path to relocate_plan_*.jsonl")
    ap.add_argument("--apply", action="store_true", help="Execute rename (default: dry-run)")
    ap.add_argument("--limit", type=int, default=0, help="Max operations to execute/print")
    args = ap.parse_args()

    plan_path = Path(args.plan)
    if not plan_path.exists():
        raise SystemExit(f"plan not found: {plan_path}")

    candidates: list[tuple[str, str]] = []
    scan_rows = 0
    for row in iter_jsonl(str(plan_path)):
        if not isinstance(row, dict) or "_meta" in row:
            continue
        scan_rows += 1
        if str(row.get("reason") or "") != "already_correct":
            continue
        src = str(row.get("src") or "")
        dst = str(row.get("dst") or "")
        if not src or not dst or src == dst:
            continue
        if src.lower() != dst.lower():
            continue
        candidates.extend(_extract_case_only_dirs(src, dst))

    ops = _normalize_ops(candidates)
    if args.limit and args.limit > 0:
        ops = ops[: args.limit]

    results: list[dict[str, Any]] = []
    ok_count = 0
    err_count = 0
    if args.apply:
        for op in ops:
            res = _rename_case_only_dir(op["old"], op["new"])
            results.append(res)
            if res.get("ok"):
                ok_count += 1
            else:
                err_count += 1
    else:
        results = [{"old": op["old"], "new": op["new"], "status": "planned"} for op in ops]

    print(
        safe_json(
            {
                "ok": err_count == 0,
                "tool": "normalize_relocate_case",
                "mode": "apply" if args.apply else "dry_run",
                "planPath": str(plan_path),
                "scannedPlanRows": scan_rows,
                "plannedCaseNormalizeOps": len(ops),
                "applied": ok_count,
                "errors": err_count,
                "operations": results,
            }
        )
    )
    return 0 if err_count == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
